<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>DisableQuestNotification</RootNamespace>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <!-- Translations -->
  <ItemGroup>
    <AdditionalFiles Include="i18n/default.json" />
  </ItemGroup>

  <!-- SMAPI Manifest -->
  <PropertyGroup>
    <Name>DisableQuestNotification</Name>
    <Authors>MonsoonSheep</Authors>
    <Description>Monsoon's Mod</Description>
    <UniqueId>MonsoonSheep.DisableQuestNotification</UniqueId>
    <UpdateKeys>Nexus:696969696969</UpdateKeys>
    <Version>1.0.0</Version>
    <MinimumApiVersion>4.5.2</MinimumApiVersion>
    <MinimumGameVersion>1.6</MinimumGameVersion>
  </PropertyGroup>

  <!-- Mod Dependencies for manifest builder -->
  <ItemGroup>
    <SMAPIDependency Include="spacechase0.GenericModConfigMenu" Version="1.12" Required="false" />
  </ItemGroup>

  
  <ItemGroup>
    <PackageReference Update="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
  </ItemGroup>

</Project>
